### ISSUE TITLE
Promotion not deleted fully

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#101]
I created a promotion called TestPromo then added some promotion content.
I deleted the promotion
I then create another promotion with the same name
When I went to add the new content, it showed the old promo content https://mazdademo.admin.kademi-qa.co/rewards/testpromo?wizard=2

Looks like a promotion is not completely deleted.

**Comment by bradmac** [comment]
> Looks like a promotion is not completely deleted.

Correct, the content is held in a repository folder. This is fine
