### ISSUE TITLE
Panel component

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#107]
Admin http://salesclaimprogram.admin.kademi-qa.co/pages/sales-claim-program/version1/Temp/
This page http://sales-claim-program_salesclaimprogram.kademi-qa.co/Temp/panels.html

The use of containers to create panels does not make sense, a panel should be a component just like a media component.

Containers - remove the panel options as containers are used to structure a page.  They are currently:
![image](https://user-images.githubusercontent.com/2201340/109759166-ba488c80-7c40-11eb-966b-fbcbfbc93fcc.png)

Delete the current component called 'Panel with solid left margin' as this is a container.

Create new component called 'Panel'.  The options should include the following:
![image](https://user-images.githubusercontent.com/2201340/109759509-39d65b80-7c41-11eb-8f52-ba4453379faf.png)

And also include:
- Padding 
- Background colour 

The border radius of the panel should come from the theme.

**Comment by bradmac** [comment]
This has already been discussed and agreed

> Containers allow components to be added. At present, that is the only element which can contain components. Since you want to add components to panels, then panels must be containers.

https://github.com/Kademi/kademi-public/issues/59
