### ISSUE TITLE
Media component looks buggy

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#109]
http://salesclaimprogram.admin.kademi-qa.co/pages/sales-claim-program/version1/claims/
Open index.html page

Option **width** should define the space between the left of the component and how far the text is pushed out.
Option **photo width** should define the width of the image only

Looks like this has changed in recent times, and needs fixing.

![image](https://user-images.githubusercontent.com/2201340/109913145-83867b00-7d01-11eb-8376-d9b11491f410.png)

**Comment by bradmac** [comment]
This looks correct to me. There is a width for the left hand section, and a width for the photo in that section

![image](https://user-images.githubusercontent.com/826458/110074665-75f6f100-7de6-11eb-868c-4ce760c30d9e.png)

**Comment by paddyow** [comment]
This looks good for me now!
