### ISSUE TITLE
Promotion Tile

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#115]
Admin http://salesclaimprogram.admin.kademi-qa.co/pages/sales-claim-program/version1/Temp/
Page http://sales-claim-program_salesclaimprogram.kademi-qa.co/Temp/promotions.html

We have two promotion components, I suggest we delete both and create a single up to date component.

![image](https://user-images.githubusercontent.com/2201340/110067063-fdcd0300-7dc6-11eb-8072-a4ca5d9469b2.png)

Options are as follows:

Full-height thumbnail (tick box)
Thumbnail height (input) - note for the panel when not in full-height mode should only adjust the the image part.
Items per row (dropdown - up to 6 only)
Max items (input) - Italics below "Leave blank to display all."
Show expired promotions (tick box)
Show finished promotions (tick box)
Period (days) @bradmac what does this do if promotions have start and end dates, do we need this?

Note the following:
Panel must adopt border radius from theme
Full height panel uses black gradient background 50% to 0%
Panel padding must adopt Vertical and Horizontal padding from theme*
Title uses H4
Sub promotion title uses P tag
Information field i.e. "Closes..." or "Winner announced.." uses a label and colour info.
Button (not full-height)  - small button and default brand colour
Button (full height thumbnail) - small button and primary brand colour

*vertical and horizontal padding

Please see the product list component.  This 'should' be using this theme parameter, so we need to make sure all components are consistent.

![image](https://user-images.githubusercontent.com/2201340/110067218-58fef580-7dc7-11eb-824b-3e82451a14ae.png)

**Comment by bradmac** [comment]
@paddyow if we delete both components then that will break every site that uses them when they upgrade

So i suggest we dont do that. But we can make one of them as deprecated, and just focus on improving the other one.

The most recently updated one is "Competition List" so lets stick with that
https://github.com/Kademi/kademi-dev/issues/10657#issuecomment-708269878

> Period (days) @bradmac what does this do if promotions have start and end dates, do we need this?

This controls how long finished promotions are displayed for. Typically with promotions that award prizes they need to be shown after the promotion period so people can see who won

**Comment by bradmac** [comment]
Done in reward-lib 3.2.3
