### ISSUE TITLE
Product list component

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#12]
http://b2bcommercesolution.admin.kademi-qa.co/pages/b2b-portal/version1/testpages/

Are we happy that our component renders space under the H tag when one product has a longer title?

1) We leave this
2) We cap the title chars by adding.... at the end, but if we do this, how do we manage the title length when we show 2 or 3 or 4 per row which varies the horizontal space where more header chars can be used when we show less prods per row.

![image](https://user-images.githubusercontent.com/2201340/91368810-5b4b2a80-e84d-11ea-9f98-3158c6e4d2ca.png)

**Comment by bradmac** [comment]
> Are we happy that our component renders space under the H tag when one product has a longer title?

Yep, looks like a common approach
![image](https://user-images.githubusercontent.com/826458/91369102-f4367180-e85e-11ea-8583-1c2ffdb11077.png)
