### ISSUE TITLE
Breadcrumb component

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#124]
This user http://salesclaimprogram.admin.kademi-qa.co/manageUsers/31453147/#summary-tab
This page http://admin-portal_salesclaimprogram.kademi-qa.co/dashboard

Breadcrumb is added to the defaultThemeTemplate

Dashboard shows the following: 
![image](https://user-images.githubusercontent.com/2201340/110875460-c52eab80-8329-11eb-8038-4bae8fbdc0f7.png)

When I click through to the claim management page, it loses the root page (being dashboard).
![image](https://user-images.githubusercontent.com/2201340/110875492-d5df2180-8329-11eb-89d1-d4b181ea6ef9.png)

Expecting:  Admin Portal / Dashboard / Review sales claims

@anhnt mentioned we don't show the dashboard as a root page, so the breadcrumb trail wont work.

**Comment by bradmac** [comment]
> When I click through to the claim management page, it loses the root page (being dashboard).

No, the dashboard is not above any other page, its beside it. So you'll never see the dashbard in the breadcrumb trail, except for when its the current page.

**Comment by bradmac** [comment]
> Review sales claims Review sales claims 

Something we can fix, is that the same page shouldnt be shown twice

**Comment by bradmac** [comment]
> @anhnt mentioned we don't show the dashboard as a root page, so the breadcrumb trail wont work.

I guess one thing we can do is to have a setting for what to consider the root page, ie dashboard or site landing page
