### ISSUE TITLE
Category importer

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#131]
http://recognitionprogram.admin.kademi-qa.co/categories/

Category name should be called 'Category Code'
![image](https://user-images.githubusercontent.com/2201340/111565360-4c2ec880-87ef-11eb-8d46-00e4303e53eb.png)

Because this is what it's called in the table - so is very confusing.
![image](https://user-images.githubusercontent.com/2201340/111565409-6799d380-87ef-11eb-9098-84c73d94b0c5.png)

**Comment by bradmac** [comment]
Done
