### ISSUE TITLE
Ksignup - renaming ORG placeholder causes file dialogue to appear

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#133]
Admin http://recognitionprogram.admin.kademi-qa.co/pages/sales-portal/version2/
Edit index.html page
Edit rego component 

When you enter a new placeholder name and click return, the file dialogue opens.

![image](https://user-images.githubusercontent.com/2201340/112074321-24ae7600-8bca-11eb-9d44-c2d516fa5571.png)

**Comment by bradmac** [comment]
> When you enter a new placeholder name and click return, the file dialogue opens.

I think you're pressing Enter .. just dont do that.
