### ISSUE TITLE
KPI progress component

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#137]
This user https://salesperformanceprogram.admin.kademi-qa.co/manageUsers/33665147/#summary-tab
This page http://sales-performance-program_salesperformanceprogram.kademi-qa.co/dashboard
![image](https://user-images.githubusercontent.com/2201340/112418756-346ebb80-8d7e-11eb-9a89-ce27781a4345.png)

The RHS component shows percentage growth towards a calculated target or 10% taken from baseline sales data.
https://salesperformanceprogram.admin.kademi-qa.co/recognition/33699911/

The component needs to show:
- actual calculated target (which could be dollars or CSI)
- actual current amount  (which could be dollars or CSI)

**Comment by bradmac** [comment]
@paddyow as discussed we will not support actual value and baseline on this component.

Just close if there's nothing else you want
