### ISSUE TITLE
KPI status component update

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#141]
This user https://salesperformanceprogram.admin.kademi-qa.co/manageUsers/33665147/#summary-tab
This page http://sales-performance-program_salesperformanceprogram.kademi-qa.co/dashboard

UI artwork 
![image](https://user-images.githubusercontent.com/2201340/112787653-be7f9280-90a4-11eb-8420-ea5f23974245.png)

1 - Progress label the admin can optionally type and show in the component above the actual progress field / P sized text / BS font colour

2 - Shows the current progress / H1 / BS font colour
2b - Allows admin to add a symbol i.e. $ or % before or after the progress field

3 - The KPI target which allows the admin to add a symbol i.e. $ or % before or after the progress field / P sized text / BS gray colour

4 - The current amount which allows the admin to add a symbol i.e. $ or % before or after the progress field / P sized text / BS gray colour

5 - Show projected progress in percent / P sized text / BS gray colour

6 - Shows the component label

Additional notes:
- when options are removed, fields must remain vertically centred
- When the container is inversed, all text must invert to white
- @bradmac what is 'Show current sales in KPI period'? is this still required?

Component configuration options to update/add
![image](https://user-images.githubusercontent.com/2201340/112788247-2edae380-90a6-11eb-8f35-966cb0024a5e.png)

**Comment by bradmac** [comment]
@paddyow as discussed, need to update to allow for what fields are standard across all metrics
