### ISSUE TITLE
Recognition levels in a journey

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#149]
This user http://recognitionprogram.admin.kademi-qa.co/manageUsers/34219968/#emailAppTab-tab
This journey http://recognitionprogram.admin.kademi-qa.co/funnels/trade-levels/version1/#journeyBuilder-tab

3 levels:
Bronze $0
Silver $50,000
Gold $100,000

Scenario is a builder goes in store and purchases 100K worth of product on day 1 so they qualify for gold.

When I add a sale for 100K, the journey triggers both level goals within the journey, I know this because the user is sent both emails that follow each goal.

But the adding of gold, and removing of the silver tags that follows the second level goal email does not work.

![image](https://user-images.githubusercontent.com/2201340/113828219-7f012680-97c7-11eb-9423-96449e84f54c.png)

![image](https://user-images.githubusercontent.com/2201340/113827427-a3a8ce80-97c6-11eb-8706-7dd8f1e750f1.png)

I can also see they are getting awarded gold twice for some reason http://recognitionprogram.admin.kademi-qa.co/manageUsers/34219968/#krecognition-achievements-tab

![image](https://user-images.githubusercontent.com/2201340/113827894-2893e800-97c7-11eb-8006-ea58918b369c.png)

**Comment by paddyow** [comment]
Adding a timer goal after the 2nd email node causes the add/remove groups to work  http://recognitionprogram.admin.kademi-qa.co/funnels/trade-levels/version1/#journeyBuilder-tab

@bradmac is this what we want?  

I am also trying to figure out why users are getting gold level twice? http://recognitionprogram.admin.kademi-qa.co/manageUsers/34221102/#krecognition-achievements-tab

Is this a bug?

![image](https://user-images.githubusercontent.com/2201340/113834240-f639b900-97cd-11eb-9f1e-7df0f3286160.png)

**Comment by bradmac** [comment]
@paddyow its a bad idea to use a journey like that, it will make it very hard to manage a large scale program.

a better way would be to use a dynamic journey, so we dont need to physically add/remove participants to groups
