### ISSUE TITLE
Setting path on contact form goal

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#150]
This journey http://kcrm.admin.kademi-qa.co/funnels/customers/version1/#journeyBuilder-tab

![image](https://user-images.githubusercontent.com/2201340/113973769-2c377580-9880-11eb-9a5c-6d3b9e0606d2.png)

If you set the path as / the goal will trigger if the URL is http://website-kcrm.kademi-qa.co/
But if the URL changes to http://website-kcrm.kademi-qa.co/index.html the goal does not trigger.

The root page can be called using either / or index.html, but the goal will only fire if you add / or index.html - not both.

**Comment by bradmac** [comment]
This is correct and intended. Just be sure to use / consistently
