### ISSUE TITLE
Kcode for sales data

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#165]
This user http://rewardsandecommerce.admin.kademi-qa.co/manageUsers/36985730/#summary-tab
This page http://partner-portal_rewardsandecommerce.kademi-qa.co/dashboard

How can we remove the decimal place?

![image](https://user-images.githubusercontent.com/2201340/119464012-b03cb280-bd85-11eb-9900-bf1d0c7b40ea.png)

**Comment by bradmac** [comment]
use the new kcode structure and with "toInteger"
