### ISSUE TITLE
Credit card and points store

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#166]
This user http://rewardsandecommerce.admin.kademi-qa.co/manageUsers/36985730/#summary-tab

- 2 stores are created, one with credit card, the other points only
- We manage this by using container vis i.e page.attributes.store.name.equals("ecommerce-store")
-- So a single template will have 2x containers showing say an order form for points, and another for credit card

The issue right now is you cannot add a reward item to cart, leave it there, then add a ecomm product to cart as it throws an error.

Do we want to address this now?

**Comment by bradmac** [comment]
> The issue right now is you cannot add a reward item to cart, leave it there, then add a ecomm product to cart as it throws an error.

No. Error message is self explanatory and thats fine for now
