### ISSUE TITLE
Cannot run incentive rule on store purchase

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#170]
When someone buys product from an store with a Credit Card, we need to setup this journey to create a data series record http://rewardsandecommerce.admin.kademi-qa.co/funnels/purchasing-journey/version1/#journeyBuilder-tab

This creates a record like this http://rewardsandecommerce.admin.kademi-qa.co/sales/sales-data/37112773

The issue is I cannot run an incentive rule that applies a point bonus on a category as this data is not passed through to the data series record.

This is the rule using the category http://rewardsandecommerce.admin.kademi-qa.co/sales/sales-data/sources/source-double-points/#general-tab

**Comment by bradmac** [comment]
@paddyow no we wont use journeys for this. Journey builders are not to be used as a programming language

lets discuss to find an appropriate way
