### ISSUE TITLE
Running points and pay store issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#175]
This recipe uses a points and pay store http://rewardsandecommerce.admin.kademi-qa.co/

It has been setup where the ecom store uses the viewStore template and dollars as a currency, then we created a web-page to show reward products using points as a currency.

This works until you drop into an email a component that shows a list of products in a store, but as the component by default clicks through the viewStore template, it goes to the default template using dollars which won't work if it needs to click through to a points store. Example http://rewardsandecommerce.admin.kademi-qa.co/funnels/nurture-journey/version1/emailAction-5fe5c7/#summary-tab

Should we not set the currency on the store page vs the component, this way we don't need to setup different templates for different types of stores.

**Comment by bradmac** [comment]
> then we created a web-page to show reward products using points as a currency.

please remove those pages

>  it goes to the default template using dollars which won't work if it needs to click through to a points store

this should go to the default page, which should be setup to work correctly

> Should we not set the currency on the store page vs the component,

maybe sometime in future, but not now. Just use container vis rules to show the right options.
