### ISSUE TITLE
Website posting twice

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#206]
Have spoken to Anh re this and he tells me the website is posting twice.

Any form on the Kademi website posts twice resulting in 2x google Ad conversions.

https://www.kademi.co/getintouch/contact/
https://www.kademi.co/getintouch/demonstration/

Both pages use a custom contact form APP.

Have tried:

Creating a test page with a standard contact form
Removing Google Tag manager
Updating website APPS
Turning off Captcha

**Comment by paddyow** [comment]
@bradmac Chris has investigated and was able to see a double post, but unable to work out why.

Advise next steps.

**Comment by bradmac** [comment]
@shubshub to continue

**Comment by shubshub** [comment]
As Discussed with Patrick, This may be something unrelated to Kademi, He is going to check on the Tag Management end to make sure its all set up correctly, We will look further into this on our end if there is still no progress made by the end of the week
