### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#210]
The following solution was working two hours ago, but now I have issues logging in.

This user http://dealregistration.admin.kademi-qa.co/manageUsers/78032960/#summary-tab

Login as this user. I see this:
![image](https://user-images.githubusercontent.com/2201340/199847565-a29bc6ad-97a5-48f1-a695-059cf58b86af.png)

The same login window shows on the edit blog page

http://dealregistration.admin.kademi-qa.co/blogs/resources/resource-1/#bodyCopy-tab

**Comment by paddyow** [comment]
Ok I have worked this out.

Login as this user http://dealregistration.admin.kademi-qa.co/manageUsers/78032960/#summary-tab

Note the portal opens fine.

Then go to this blog in the admin http://dealregistration.admin.kademi-qa.co/blogs/resources/resource-1/#bodyCopy-tab
Click preview and you'll see the login dialogue - which is wrong, it normally show the blog page

Then go back to the previous profile and login http://dealregistration.admin.kademi-qa.co/manageUsers/78032960/#summary-tab

You can no longer login as a profile.

Looks like when you preview a blog, its causing some login issue that I have not seen before.

**Comment by shubshub** [comment]
In the logs when trying to access the website I see

```Invalid userUrl hash, possible attempted hacking attempt. userUrl=/users/frank/22:53:59
INFOauthorise: isForceLogin: not user so reject authorisation22:53:59
WARNauthorisation declined, requesting authentication: /dashboard. resource type: io.milton.cloud.server.apps.user.DashboardPage22:53:59
INFOauthorisation failed. respond with: co.kademi.server.web.KademiResponseHandler resource: io.milton.cloud.server.apps.user.DashboardPage```

![image](https://user-images.githubusercontent.com/413964/199850403-5294001e-2687-413f-973a-312d89f40fb2.png)
And then I am met with this
![image](https://user-images.githubusercontent.com/413964/199850447-4565f7c2-39d0-4834-9c5a-024192ed032d.png)
