### ISSUE TITLE
Add icon support to media component

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#212]
I want to standardise features in the solutions and not use image icons if possible.

Can we add support to the media component and have the option to use an icon vs an image?

![image](https://user-images.githubusercontent.com/2201340/201027603-0632ac73-b957-4795-9cb0-dc509962cd14.png)

I would also be good to be able to insert a single icon on a page, not sure if this needs its own component. For example:

![image](https://user-images.githubusercontent.com/2201340/201027792-4db8296b-533f-45aa-ba41-54b1828436ac.png)

**Comment by bradmac** [comment]
> Can we add support to the media component and have the option to use an icon vs an image?

https://github.com/Kademi/kademi-dev/issues/15687

> I would also be good to be able to insert a single icon on a page, not sure if this needs its own component.

We already have this in ckeditor:

![image](https://user-images.githubusercontent.com/826458/201208539-a5ea6cb7-1c7b-46c3-a42d-8ba85402927c.png)

I think you can get the layout you want using existing container layout options
