### ISSUE TITLE
Trigger a task node in KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#214]
https://kcrm.kademi.co/leads/244852077/

Sometimes I want to trigger a task node in a journey from the KCRM lead page. Is this possible? At the moment I have to go into the admin console to do this.

If not, might be a nice feature to support where you can select a journey node from the lead page.

**Comment by bradmac** [comment]
> Sometimes I want to trigger a task node in a journey from the KCRM lead page

that should be done by choosing an outcome like we do with SRs
