### ISSUE TITLE
Order status goal needs options

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#25]
http://b2bcommercesolution.admin.kademi-qa.co/funnels/purchasing-journey/version1/#journeyBuilder-tab

Need timeout option added to node at a minimum. 
Need to add journey stage

![image](https://user-images.githubusercontent.com/2201340/92552759-b4cb4480-f2a4-11ea-8c0d-49c21318f9d7.png)

**Comment by bradmac** [comment]
Moved to kademi-dev
