### ISSUE TITLE
Data series value goal needs timeout options

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#26]
http://b2bcommercesolution.admin.kademi-qa.co/funnels/customer-journey/version1/#journeyBuilder-tab

Data series value node

![image](https://user-images.githubusercontent.com/2201340/93548778-517b9980-f9ab-11ea-9c75-16954fbe493a.png)

- needs timeout options
- need stages options

**Comment by bradmac** [comment]
Moved to https://github.com/Kademi/kademi-dev/issues/10709
