### ISSUE TITLE
Dashboard Content

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#3]
Client suggested Kademi has the ability to setup more than one dashboard template where there are multiple programs in a single account that have a lot of varying content on the dashboard.

"While I like the idea of having all the programs consolidated into one dashboard.  Then, having the dashboard dynamically display the right components to the right participants.  I can see it being horribly confusing for the Program Manager or Administrator if they need to change any messaging to various participant groups over the course of the program.  Consolidating XXXXX Administrator views into the dashboard to approve XXXX sales might make it even more confusing .  There’s also lots of different participant types in the  Dealer program that may need different views.  Would it makes sense to have (2) different dashboards for the Preferred Partner Program (both US and Canada) and the  XXXX Dealer Program just to make it easier and more understandable for Program Managers and Administrators?"

**Comment by bradmac** [comment]
Kademi has a concept of a dashboard which is integrated into many different parts of the platform

This dashboard is always at a specific address: /dashboard

Creating different pages which show a different dashboard for each type of user will cause conflicts with those parts of the kademi platform which assume a standard location for the dashboard

Anything is possible, but its best to stick with the easy option where we can. In this case its using a single dashboard page.
