### ISSUE TITLE
Recommended for me option causes page error

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#34]
Edit dashboard http://b2bcommercesolution.admin.kademi-qa.co/pages/b2b-portal/version2/

Edit Product List Settings

Choose option "recommended for me?"

Error

Error rendering component: storeProductList
class org.apache.velocity.exception.MethodInvocationException - Invocation of method 'addAll' in class java.util.ArrayList threw exception java.lang.NullPointerException at b2b-portal_b2bcommercesolution.kademi-qa.co:/theme/apps/KCommerce2/components/storeProductListComponent.html[line 91, column 37]

**Comment by bradmac** [comment]
fixed
