### ISSUE TITLE
Targeting promotions using ORGs

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#35]
Speaking with Oppo Mobile, the one thing that jumped out and aligned with them was the ability to quickly run a promotion that targeted a region.  This for them was tactical and highly advantageous. 

It would make sense that a promotion can be setup, then an Org selected, which if it has child orgs, it cascades.

For example these orgs http://b2bcommercesolution.admin.kademi-qa.co/organisations/?q=

I have country > state > sales region > retail store

From the promotion page here http://b2bcommercesolution.admin.kademi-qa.co/rewards/25-off-something/#groups-tab

It would be good to select a territory http://b2bcommercesolution.admin.kademi-qa.co/organisations/?q=&term-orgTypes=territory

....which then makes that promotion available to all orgs in that territory.

**Comment by bradmac** [comment]
@paddyow that can be done now with pricing rules. 

The logic for targeting pricing rules is potentially very complex (not just orgs), and we dont want to try to replicate it in promotion config
