### ISSUE TITLE
Promo + pricing rule does not work

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#37]
This promo http://b2bcommercesolution.admin.kademi-qa.co/rewards/25-of-watches/#details-tab
This pricing rule http://b2bcommercesolution.admin.kademi-qa.co/websites/b2b-portal/version2/store-b2b-portal-ecomstore/?ruleNum=2

When you use the promo the pricing rule does not work, when you remove the promo from the pricing rule, the pricing rule works.

This user http://b2bcommercesolution.admin.kademi-qa.co/manageUsers/25874746/#summary-tab

Go to store, and select the category watches.

**Comment by LYNP88** [comment]
I've checked and it works fine now, just remove the duplicated pricing rule and clear caches!
