### ISSUE TITLE
Wishlist not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#44]
This user http://shophq.admin.kademi-qa.co/manageUsers/26111353/#summary-tab
Login and go to store
Click add to Wishlist button
Getting error

**Comment by anhnt** [comment]
Make sure you dont create a static folder called `wishlist`, use this instead
![image](https://user-images.githubusercontent.com/735555/94124180-e5070b80-fe7e-11ea-8059-09d691a79dc7.png)
