### ISSUE TITLE
Date range Default range not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#5]
https://kademitest.dropboxacademy-dbxacademy.kademi.com.au//theme/apps/user/contenteditor?fileName=profile.html

Selecting a date range on the Date Range Settings component does not reflect in the front-end.

Does this look like a bug?  Or is there something I should look at first.

![image](https://user-images.githubusercontent.com/2201340/64842541-d4a23b00-d645-11e9-9d38-927f0434b587.png)

![image](https://user-images.githubusercontent.com/2201340/64842584-f69bbd80-d645-11e9-934f-859486f4adde.png)

**Comment by bradmac** [comment]
> Does this look like a bug? Or is there something I should look at first.

note this will only have any effect if you havent viewed that page already, since if you have a cookie will have been saved with the previous range

so try again after clearing cookies

**Comment by paddyow** [comment]
Cleared cookies, logged in again and the date range did not reflect the range set on the component.

**Comment by bradmac** [comment]
admin: https://dbxacademy.admin.kademi.com.au/

**Comment by bradmac** [comment]
looks good to me

![image](https://user-images.githubusercontent.com/826458/64930792-f854c380-d887-11e9-885f-446a10ef1473.png)

test user: https://dbxacademy.admin.kademi.com.au/manageUsers/168391889/#summary-tab
