### ISSUE TITLE
Option to remove menu bottom padding?

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#51]
Admin http://kademiuifixes.admin.kademi-qa.co/pages/sales-incentive-example/version1/
FE http://sales-incentive-example_kademiuifixes.kademi-qa.co/

Looks bad when adding say a carousel or image at the top of the page, and it does not sit flush with the top menu area.

![image](https://user-images.githubusercontent.com/2201340/100294662-90e1ea00-2fdb-11eb-9d71-5a05e92dab3f.png)

**Comment by bradmac** [comment]
Moved to https://github.com/Kademi/kademi-dev/issues/11098
