### ISSUE TITLE
Hardcoding paddings and margins

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#52]
Admin http://kademiuifixes.admin.kademi-qa.co/pages/sales-incentive-example/version1/
FE http://sales-incentive-example_kademiuifixes.kademi-qa.co/

Hardcoding paddings and margins creates a poor responsive experience where the value does not change for smaller screens.

Desktop padding looks good
![image](https://user-images.githubusercontent.com/2201340/100294733-bf5fc500-2fdb-11eb-94b3-e1ceb1dc8131.png)

Mobile breakpoint looks poor as the padding has not responded.
![image](https://user-images.githubusercontent.com/2201340/100293713-adc8ee00-2fd8-11eb-9f4b-3166cde41a69.png)

Should respond and look something like this:
![image](https://user-images.githubusercontent.com/2201340/100294814-fcc45280-2fdb-11eb-8891-5c2712e4b8fb.png)

**Comment by bradmac** [comment]
@paddyow what you're doing here is exactly what the jumbotron is intended for

So please use that instead of customising padding

**Comment by paddyow** [comment]
A jumbotron does not support a BG image, nor does it allow you to add 'transparent' to the BG colour.

![image](https://user-images.githubusercontent.com/2201340/100296558-b32a3680-2fe0-11eb-8840-edbc8e56bd16.png)

**Comment by bradmac** [comment]
Moved to https://github.com/Kademi/kademi-dev/issues/11100
