### ISSUE TITLE
KSignup form button does not match input sizes

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#53]
Admin http://kademiuifixes.admin.kademi-qa.co/pages/sales-incentive-example/version1/
FE http://sales-incentive-example_kademiuifixes.kademi-qa.co/

Changing the input size on the Ksignup form does not change the button size.  They should mirror in height.

![image](https://user-images.githubusercontent.com/2201340/100294859-25e4e300-2fdc-11eb-8773-4001642e9402.png)

**Comment by bradmac** [comment]
Moved to https://github.com/Kademi/kademi-dev/issues/11097
