### ISSUE TITLE
Menu Padding/Margin

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#54]
Admin http://sales-incentive-example_kademiuifixes.kademi-qa.co/
FE http://sales-incentive-example_kademiuifixes.kademi-qa.co/dashboard

Menu component has no margin around it, so the buttons sit flush to the edge of the screen - which looks bad.

![image](https://user-images.githubusercontent.com/2201340/100294978-74927d00-2fdc-11eb-92a5-e21968530448.png)

To fix this I added a margin around the container the menu sits in.

![image](https://user-images.githubusercontent.com/2201340/100295034-a1469480-2fdc-11eb-854b-e3aa0d1024f6.png)

If we are happy with this approach, we can close this issue.

**Comment by bradmac** [comment]
Yep, i think thats fine
