### ISSUE TITLE
Text component bottom padding/margin not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#55]
Admin http://kademiuifixes.admin.kademi-qa.co/
Page http://sales-incentive-example_kademiuifixes.kademi-qa.co/contenteditor?fileName=test-page.htm
FE http://sales-incentive-example_kademiuifixes.kademi-qa.co/test-page.html

![image](https://user-images.githubusercontent.com/2201340/100295908-fdaab380-2fde-11eb-9d5b-7e8df6021a64.png)

**Comment by bradmac** [comment]
Moved to https://github.com/Kademi/kademi-dev/issues/11099
