### ISSUE TITLE
More UI components

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#56]
Have a broader range of UI components that can be dropped into a page UI.

This user http://kademiuifixes.admin.kademi-qa.co/manageUsers/28306462/#summary-tab

I want a new type of panel to drop in where the admin can insert images and text.

![image](https://user-images.githubusercontent.com/2201340/100296073-61cd7780-2fdf-11eb-8417-440b8339e65d.png)

I have to create my own class to do this http://kademiuifixes.admin.kademi-qa.co/repositories/sales-incentive-example/version1/theme/texteditor?fileName=theme-params.less

**Comment by paddyow** [comment]
This user http://kademiuifixes.admin.kademi-qa.co/manageUsers/28306462/#summary-tab

Dropped in a BS Panel. 

Have not way to control the text padding.

**Comment by paddyow** [comment]
This is an example of a custom class used to build a panel:

This user http://kademiuifixes.admin.kademi-qa.co/manageUsers/28306462/#summary-tab
This page http://sales-incentive-example_kademiuifixes.kademi-qa.co/dashboard-test.html
This class http://kademiuifixes.admin.kademi-qa.co/repositories/sales-incentive-example/version1/theme/texteditor?fileName=theme-params.less

Looks like this
![image](https://user-images.githubusercontent.com/2201340/100297444-ce964100-2fe2-11eb-9fe8-760bf2c41edb.png)

**Comment by bradmac** [comment]
Moved to https://github.com/Kademi/kademi-dev/issues/11101
