### ISSUE TITLE
Text component seems to be defaulting as a link

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#57]
This user http://kademiuifixes.admin.kademi-qa.co/manageUsers/28306462/#summary-tab
This page http://sales-incentive-example_kademiuifixes.kademi-qa.co//theme/apps/user/contenteditor?fileName=dashboard.html

Text is showing as blue
![image](https://user-images.githubusercontent.com/2201340/100298247-b9221680-2fe4-11eb-9c4e-a975df81ce21.png)

Has a hover effect (goes darker) when you roll over
![image](https://user-images.githubusercontent.com/2201340/100298355-07371a00-2fe5-11eb-8864-a33e252b799b.png)

Has a colour of #000000 in Keditor.

Looks like it's functioning as a link, when it should not.

**Comment by bradmac** [comment]
Yep, i noted that on the other issue for a text component already
