### ISSUE TITLE
Menu buttons

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#6]
http://johnsmanville.admin.kademi-qa.co/pages/johns-manville/v2-live/

http://johns-manville-kcrm_johnsmanville.kademi-qa.co//theme/contenteditor?fileName=defaultThemeTemplate.html

The menu component on the JM website seems to be referencing menu items setup on a 2nd website for leadman here http://johnsmanville.admin.kademi-qa.co/pages/johns-manville-kcrm/version1/

The menu items in the JM website cannot be removed.

![image](https://user-images.githubusercontent.com/2201340/64951495-58b42700-d8c1-11e9-8695-837d8e6660bf.png)

**Comment by bradmac** [comment]
> The menu items in the JM website cannot be removed.

This is correct. System provided menus can only be hidden, not removed
