### ISSUE TITLE
Add custom fonts

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#85]
Admin http://oppo.admin.kademi.com.au/

How do we want a non technical customer to add a custom font?

Dropping @import '/theme/fonts.less'; into the less file, breaks the style editor where a customer cannot edit any as all the fields appear blank.

What is the approach we want a customer to go through to do this, and do we need to add any GUI options?

**Comment by bradmac** [comment]
We have this in docs
https://docs.kademi.co/programs/dxpfundamentals/dxfp3/dxfp3-020/pupdating-the-less-file.html

No, i dont think we try to integrate with the UI. Instead, it would be best to have fonts in themes and users can select a theme

If someone does want to use a custom theme then it will require someone to update the less file as per the tutorial

**Comment by paddyow** [comment]
Adding the code: 


@font-face {
    font-family: 'OPPO Sans';
    src: url('/theme/fonts/OPPOSans-BoldItalic.woff2') format('woff2'),
        url('/theme/fonts/OPPOSans-BoldItalic.woff') format('woff');
    font-weight: bold;
    font-style: italic;
    font-display: swap;
}

**Comment by bradmac** [comment]
the theme-params.less file must only contain parameters

the font face stuff above needs to go in a different file

**Comment by paddyow** [comment]
Then this training doc is incorrect https://docs.kademi.co/programs/dxpfundamentals/dxfp3/dxfp3-020/pupdating-the-less-file.html

 Anh created this file http://oppo.admin.kademi.com.au/repositories/oppo-star-points/version1/theme/texteditor?fileName=fonts.less

And referenced it in the less file as  @import '/theme/fonts.less';

But this approach breaks the style editor.

So I am not sure how this should be done....

**Comment by bradmac** [comment]
Yep. Need to add a custom CSS or LESS file as per the dev tutorial

https://docs.kademi.co/programs/dev/d0/d07/padding-dependencies-to-your-website.html

**Comment by bradmac** [comment]
This issue has been replaced with https://github.com/Kademi/kademi-public/issues/85
