### ISSUE TITLE
Ktoolbar

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#86]
Log into this account http://kademiuifixes.admin.kademi-qa.co/pages/sales-incentive-example/version3/
View test page - do you see the Ktoolbar?
If not, edit the test page in Keditor
Close
View test page and you will see Ktoolbar

Looks like you need to edit a webpage first before you can view the Ktoolbar, which doesn't seem right.

**Comment by bradmac** [comment]
> View test page - do you see the Ktoolbar?

You must be logged in as an admin to see ktoolbar. If you click "View" you are not logged in
