### ISSUE TITLE
Date picker issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#95]
Issue: The dashboard shows a leader board for the current period, KPI using a date picker.  On page load the two components show correctly.
https://mazda-portal_mazdademo.kademi-qa.co/dashboard
![image](https://user-images.githubusercontent.com/2201340/108642354-cb82f200-74f8-11eb-9beb-64d59d0a5771.png)

If you go to the profile page and change the date, then go back to the dashboard the data is lost because the date has changed.
https://mazda-portal_mazdademo.kademi-qa.co/profile/
![image](https://user-images.githubusercontent.com/2201340/108642361-d9d10e00-74f8-11eb-9ee5-acc7ab3c57c1.png)

This can be tested using this profile https://mazdademo.admin.kademi-qa.co/manageUsers/30842257/#summary-tab

How can we prevent this from happening?

- Assumed the leaderboard would not be affected by the date picker as it's default is to show the current period only
- Should we create a KPI component that only shows the current period and is not affected by the date picker?

**Comment by bradmac** [comment]
> Assumed the leaderboard would not be affected by the date picker as it's default is to show the current period only

If you select "current period" then it should show results for the current period

**Comment by bradmac** [comment]
leaderboard component fixed
I've also hacked the override of the status component to use the current date. Assigned an issue to @anhnt to make that a setting later
